---
name: commit

on:
  push:

jobs:
  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: make install-front build-front
