---
name: commit

on:
  push:

jobs:
  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build frontend
        run: cd frontend && npm run preview
